### ISSUE TITLE
flickering beams

### ISSUE THREAD

**Issue by nanawuu** [GAMMACASE/ShowPlayerClips#1]
beams seem to flicker/disappear/not drawn at all if there's many clips on the screen at the same time, the plugin also causes bhop timer zone beams to flicker for some reason when !showclips is enabled o:

edit: on css :p

**Comment by GAMMACASE** [comment]
Can you tell me on what map you experience these problems, and what platform (windows or linux)? Also increasing ``spc_beams_refresh_rate`` may help with flickering issue. Soon enough I'll push update where it will draw only verts that is around you, that should resolve that flickering issue without rising ``spc_beams_refresh_rate`` up.

**Comment by nanawuu** [comment]
on bhop_alone in the slide area there's lot's of beams that won't be drawn until u get really close to them, same issue on bhop_brax.

platform is linux ^^

**Comment by GAMMACASE** [comment]
Alright I think css can't handle that many beams and at some point just stops drawing them when they are "far" away, so don't think I can do anything against it. But I did improve how they are drawn so it should be faster and less flickering.

**Comment by nanawuu** [comment]
this update fixed all of the issues, thank you! :)
