### ISSUE TITLE
Csgo Update 02/02/2023 breake the gamedata 

### ISSUE THREAD

**Issue by freakexeuLow** [GAMMACASE/ShowPlayerClips#10]
**OS and Game used:**
- OS: Linux
- Game: Csgo

**Issue description:**
L 02/03/2023 - 20:55:50: [SM] Exception reported: Failed to get "PolyFromPlane" signature.
L 02/03/2023 - 20:55:50: [SM] Blaming: showplayerclips.smx
L 02/03/2023 - 20:55:50: [SM] Call stack trace:
L 02/03/2023 - 20:55:50: [SM]   [0] SetFailState
L 02/03/2023 - 20:55:50: [SM]   [1] Line 480, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\showplayerclips.sp::SetupSDKCalls
L 02/03/2023 - 20:55:50: [SM]   [2] Line 114, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\showplayerclips.sp::OnPluginStart
L 02/03/2023 - 20:55:50: [SM] Unable to load plugin "showplayerclips.smx": Error detected in plugin startup (see error logs)

thanks again for the quick fixes of the other plugins, wanted to report this here too

**Comment by GAMMACASE** [comment]
Known, currently working on it

**Comment by GAMMACASE** [comment]
Should now be fixed
