### ISSUE TITLE
Plugin not working !?

### ISSUE THREAD

**Issue by DaigoBhop** [GAMMACASE/ShowPlayerClips#5]
Hello , the plugin not working on my server.

I have this error :

L 06/08/2020 - 22:25:27: [SM] Exception reported: Client index 0 is invalid
L 06/08/2020 - 22:25:27: [SM] Blaming: showplayerclips.smx
L 06/08/2020 - 22:25:27: [SM] Call stack trace:
L 06/08/2020 - 22:25:27: [SM]   [0] GetClientUserId
L 06/08/2020 - 22:25:27: [SM]   [1] Line 408, D:\Utilites\SteamCMD\aimservcsgo\csgo\addons\sourcemod\scripting\showplayerclips.sp::SM_ShowClipBrushes

Help pls :)

**Comment by GAMMACASE** [comment]
You shouldn't use showplayerclips command via server console or rcon.
